name: Create Test Workflow
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Create Test Workflow
              run: echo "Create Test Workflow"

            - name: checkout repository
              uses: actions/checkout@v4

            - name: Continue README file
              run: cat README.md
